---

- name: Install and manage PostgreSQL
  hosts: galaxy-host
  remote_user: "{{ remote_user }}"
  pre_tasks:
    - name: Install psycopg2
      yum:
        name: python-psycopg2
      become: yes
  roles:
    - postgresql
  tags: postgres

- name: Manage PostgreSQL users, groups, databases, and permissions
  hosts: galaxy-host
  vars:
    postgresql_objects_users:
      - name: galaxy
        password: null
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: postgres
  roles:
    - postgresql-objects
  tags: postgres

- name: Install and manage nginx
  hosts: galaxy-host
  remote_user: "{{ remote_user }}"
  roles:
    - nginx
  tags: nginx

- name: Install Galaxy
  hosts: galaxy-host
  vars:
    galaxy_server_dir: /srv/galaxy/server
    galaxy_config_dir: /srv/galaxy/config
    galaxy_mutable_server_dir: /var/galaxy/server
    galaxy_mutable_config_dir: /var/galaxy/config
    galaxy_config_style: yaml
    galaxy_config:
      galaxy:
        admin_users: eslerm@umn.edu
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
  pre_tasks:
    - name: Install Dependencies
      yum:
        name: "{{ item }}"
      become: yes
      with_items:
        - git
        - vim
        - python-virtualenv
  roles:
    - role: galaxy
      become: yes
      become_user: galaxy
  tags: galaxy
