---

- name: "Configure server for install"
  hosts: galaxy-host
  pre_tasks:
    - name: "Create galaxy user"
      user:
        name: galaxy
        #uid:
        #group:
      become: yes
    - name: "Create galaxy directory"
      file:
        path: /srv/galaxy/server
        #path: {{ foo }}
        state: directory
        owner: galaxy
        group: galaxy
        #mode:
      become: yes

- name: 'Install and manage PostgreSQL'
  hosts: galaxy-host
  pre_tasks:
    - name: Install psycopg2
      yum:
        name: python-psycopg2
      become: yes
  roles:
    - postgresql
  tags: postgres

- name: 'Manage PostgreSQL users, groups, databases, and permissions'
  hosts: galaxy-host
  vars:
    postgresql_objects_users:
      - name: galaxy
        password: null
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
  roles:
    - postgresql-objects
  tags: postgres

- name: 'Install and manage nginx'
  hosts: galaxy-host
  roles:
    - nginx
  tags: nginx

- name: 'Install Galaxy'
  hosts: galaxy-host
  vars:
    galaxy_server_dir: /srv/galaxy/server
    galaxy_config_style: yaml
    galaxy_config:
      galaxy:
        admin_users: eslerm@umn.edu
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
  pre_tasks:
    - name: Install Dependencies
      yum:
        name: "{{ item }}"
      with_items:
        - git
        - vim
        - python-virtualenv
      become: yes
  roles:
    - role: galaxy
      become_user: galaxy
  tags: galaxy
