---
# Install Galaxy server

- name: "Install Galaxy"
  hosts: galaxy-host
  vars:
    galaxy_server_dir: /srv/galaxy/server
    galaxy_config_style: yaml
    galaxy_config:
      galaxy:
        admin_users: eslerm@umn.edu
  roles:
    - role: galaxy-os
    - role: galaxy
      become_user: galaxy
