---
# use the proxy_pass branch for this playbook to run

- name: 'Install and manage nginx'
  hosts: galaxy-host
  vars:
    nginx_proxy_pass: http://127.0.0.1:8080
  roles:
    - nginx
  tags: nginx
